api/src/Model/Blog/Entity/Author/Author.php
<?php

declare(strict_types=1);

namespace App\Model\Blog\Entity\Author;

use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="blog_authors")
 */
class Author
{
    /**
     * @ORM\Column(type="blog_author_id")
     * @ORM\Id
     */
    private Id $id;
    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private DateTimeImmutable $date;
    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private DateTimeImmutable $updateDate;
    /**
     * @ORM\Embedded(class="Name")
     */
    private Name $name;
    /**
     * @ORM\Column(type="blog_author_email")
     */
    private ?Email $email = null;
    /**
     * @ORM\Column(type="blog_author_status", length=16)
     */
    private Status $status;
    /**
     * @ORM\Version()
     * @ORM\Column(type="integer")
     */
    private int $version;

    public function __construct(Id $id, Name $name, Email $email)
    {
        $this->id = $id;
        $this->name = $name;
        $this->email = $email;
        $this->date = new DateTimeImmutable();
        $this->status = Status::active();
    }

    public function edit(Name $name, Email $email): void
    {
        $this->name = $name;
        $this->email = $email;
        $this->updateDate = new DateTimeImmutable();
    }

    public function archive(): void
    {
        if ($this->status->isArchived()) {
            throw new \DomainException('Автор уже в архиве.');
        }
        $this->status = Status::archived();
    }

    public function reinstate(): void
    {
        if ($this->status->isActive()) {
            throw new \DomainException('Автор уже активен.');
        }
        $this->status = Status::active();
    }

    public function isActive(): bool
    {
        return $this->status->isActive();
    }

    public function isArchived(): bool
    {
        return $this->status->isArchived();
    }

    public function getId(): Id
    {
        return $this->id;
    }

    public function getDate(): DateTimeImmutable
    {
        return $this->date;
    }

    public function getName(): Name
    {
        return $this->name;
    }

    public function getEmail(): Email
    {
        return $this->email;
    }

    public function getStatus(): Status
    {
        return $this->status;
    }
}

api/src/Model/Blog/Entity/Author/AuthorRepository.php
<?php

declare(strict_types=1);

namespace App\Model\Blog\Entity\Author;

use App\Model\EntityNotFoundException;
use Doctrine\ORM\EntityManagerInterface;

class AuthorRepository
{
    public function __construct(
        private EntityManagerInterface $em
    ) {
    }

    public function has(Id $id): bool
    {
        return $this->em->getRepository(Author::class)->createQueryBuilder('t')
                ->select('COUNT(t.id)')
                ->andWhere('t.id = :id')
                ->setParameter(':id', $id->getValue())
                ->getQuery()->getSingleScalarResult() > 0;
    }

    public function get(Id $id): Author
    {
        if (!$author = $this->em->getRepository(Author::class)->find($id->getValue())) {
            throw new EntityNotFoundException('Автор не найден.');
        }

        return $author;
    }

    public function add(Author $author): void
    {
        $this->em->persist($author);
    }
}

api/src/Model/Blog/Entity/Author/Email.php
<?php

declare(strict_types=1);

namespace App\Model\Blog\Entity\Author;

use JetBrains\PhpStorm\Pure;
use Webmozart\Assert\Assert;

class Email
{
    public function __construct(
        private ?string $value = null,
    ) {
        Assert::notEmpty($value);
        if (!filter_var($value, FILTER_VALIDATE_EMAIL)) {
            throw new \InvalidArgumentException('Incorrect email.');
        }
        $this->value = mb_strtolower($value);
    }

    public function getValue(): string
    {
        return $this->value;
    }

    #[Pure]
    public function isEqual(self $other): bool
    {
        return $this->getValue() === $other->getValue();
    }
}

api/src/Model/Blog/Entity/Author/EmailType.php
<?php

declare(strict_types=1);

namespace App\Model\Blog\Entity\Author;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\StringType;
use JetBrains\PhpStorm\Pure;

class EmailType extends StringType
{
    public const NAME = 'blog_author_email';

    #[Pure]
    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        return $value instanceof Email ? $value->getValue() : $value;
    }

    public function convertToPHPValue($value, AbstractPlatform $platform): ?Email
    {
        return !empty($value) ? new Email($value) : null;
    }

    public function getName(): string
    {
        return self::NAME;
    }

    public function requiresSQLCommentHint(AbstractPlatform $platform): bool
    {
        return true;
    }
}

api/src/Model/Blog/Entity/Author/Id.php
<?php

declare(strict_types=1);

namespace App\Model\Blog\Entity\Author;

use JetBrains\PhpStorm\Pure;
use Ramsey\Uuid\Uuid;

class Id
{
    public function __construct(
        private ?string $value = null,
    ) {
    }

    public static function next(): self
    {
        return new self(Uuid::uuid4()->toString());
    }

    #[Pure]
    public function isEqual(self $other): bool
    {
        return $this->getValue() === $other->getValue();
    }

    public function getValue(): ?string
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}

api/src/Model/Blog/Entity/Author/IdType.php
<?php

declare(strict_types=1);

namespace App\Model\Blog\Entity\Author;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\GuidType;
use JetBrains\PhpStorm\Pure;

class IdType extends GuidType
{
    public const NAME = 'blog_author_id';

    #[Pure]
    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        return $value instanceof Id ? $value->getValue() : $value;
    }

    public function convertToPHPValue($value, AbstractPlatform $platform): ?Id
    {
        return !empty($value) ? new Id($value) : null;
    }

    public function getName(): string
    {
        return self::NAME;
    }

    public function requiresSQLCommentHint(AbstractPlatform $platform): bool
    {
        return true;
    }
}

api/src/Model/Blog/Entity/Author/Name.php
<?php

declare(strict_types=1);

namespace App\Model\Blog\Entity\Author;

use Doctrine\ORM\Mapping as ORM;
use Webmozart\Assert\Assert;

/**
 * @ORM\Embeddable
 */
class Name
{
    /**
     * @ORM\Column(type="string")
     */
    private ?string $first = null;
    /**
     * @ORM\Column(type="string")
     */
    private ?string $last = null;

    public function __construct(?string $first = null, ?string $last = null)
    {
        Assert::notEmpty($first);
        Assert::notEmpty($last);

        $this->first = $first;
        $this->last = $last;
    }

    public function getFirst(): string
    {
        return $this->first;
    }

    public function getLast(): string
    {
        return $this->last;
    }

    public function getFull(): string
    {
        return $this->first.' '.$this->last;
    }
}

api/src/Model/Blog/Entity/Author/Status.php
<?php

declare(strict_types=1);

namespace App\Model\Blog\Entity\Author;

use JetBrains\PhpStorm\Pure;
use Webmozart\Assert\Assert;

class Status
{
    public const ACTIVE = 'active';
    public const ARCHIVED = 'archived';

    private string $name;

    public function __construct(string $name)
    {
        Assert::oneOf($name, [
            self::ACTIVE,
            self::ARCHIVED,
        ]);

        $this->name = $name;
    }

    public static function active(): self
    {
        return new self(self::ACTIVE);
    }

    public static function archived(): self
    {
        return new self(self::ARCHIVED);
    }

    #[Pure]
    public function isEqual(self $other): bool
    {
        return $this->getName() === $other->getName();
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function isActive(): bool
    {
        return self::ACTIVE === $this->name;
    }

    public function isArchived(): bool
    {
        return self::ARCHIVED === $this->name;
    }
}

api/src/Model/Blog/Entity/Author/StatusType.php
<?php

declare(strict_types=1);

namespace App\Model\Blog\Entity\Author;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\StringType;
use JetBrains\PhpStorm\Pure;

class StatusType extends StringType
{
    public const NAME = 'blog_author_status';

    #[Pure]
    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        return $value instanceof Status ? $value->getName() : $value;
    }

    public function convertToPHPValue($value, AbstractPlatform $platform): ?Status
    {
        return !empty($value) ? new Status($value) : null;
    }

    public function getName(): string
    {
        return self::NAME;
    }

    public function requiresSQLCommentHint(AbstractPlatform $platform): bool
    {
        return true;
    }
}

api/src/Model/Blog/Entity/Categories/Category/Category.php
<?php

declare(strict_types=1);

namespace App\Model\Blog\Entity\Categories\Category;

use App\Model\AggregateRoot;
use App\Model\Blog\Entity\Author\Author;
use App\Model\Blog\Entity\Posts\Post\Post;
use App\Model\EventsTrait;
use App\Model\SeoProcessable;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="blog_categories_categories", indexes={
 *     @ORM\Index(columns={"date", "sort"})
 * })
 */
class Category implements AggregateRoot, SeoProcessable
{
    use EventsTrait;

    /**
     * @ORM\Column(type="blog_categories_category_id")
     * @ORM\Id
     */
    private Id $id;
    /**
     * @ORM\ManyToMany(targetEntity="App\Model\Blog\Entity\Posts\Post\Post", inversedBy="categories")
     * @ORM\OrderBy({"name" = "ASC"})
     */
    private Collection $posts;
    /**
     * @ORM\ManyToOne(targetEntity="App\Model\Blog\Entity\Author\Author")
     * @ORM\JoinColumn(name="author_id", referencedColumnName="id", nullable=false, onDelete="CASCADE")
     */
    private Author $author;
    /**
     * @ORM\Column(type="string")
     */
    private string $name;
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $description = null;
    /**
     * @ORM\Column(type="string", unique=true)
     */
    private string $slug;
    /**
     * @ORM\Embedded(class="Seo")
     */
    private Seo $seo;
    /**
     * @ORM\Embedded(class="Meta")
     */
    private Meta $meta;
    /**
     * @ORM\Column(type="blog_categories_category_status", length=16, options={"default" : Status::ACTIVE})
     */
    private Status $status;
    /**
     * @ORM\Column(type="integer", options={"default" : 0})
     */
    private int $sort;
    /**
     * @ORM\OneToMany(
     *     targetEntity="Category",
     *     mappedBy="parent"
     * )
     */
    private Collection $children;
    /**
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="children")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", nullable=true)
     */
    private ?Category $parent = null;
    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private DateTimeImmutable $date;
    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private DateTimeImmutable $updateDate;
    /**
     * @ORM\Version()
     * @ORM\Column(type="integer")
     */
    private int $version;

    public function __construct(
        Id $id,
        Author $author,
        string $name,
        DateTimeImmutable $date,
        string $slug,
        Seo $seo,
        Meta $meta,
        int $sort,
        ?Category $parent = null,
        ?string $description = null
    ) {
        $this->id = $id;
        $this->author = $author;
        $this->name = $name;
        $this->description = $description;
        $this->date = $date;
        $this->slug = $slug;
        $this->seo = $seo;
        $this->meta = $meta;
        $this->sort = $sort;
        $this->parent = $parent;
        $this->status = new Status(Status::ACTIVE);
        $this->posts = new ArrayCollection();
        $this->children = new ArrayCollection();
    }

    public function edit(
        string $name,
        string $slug,
        Seo $seo,
        Meta $meta,
        int $sort,
        ?Category $parent = null,
        ?string $description = null
    ): void {
        $this->name = $name;
        $this->slug = $slug;
        $this->seo = $seo;
        $this->meta = $meta;
        $this->sort = $sort;
        $this->parent = $parent;
        $this->description = $description;
        $this->updateDate = new DateTimeImmutable();
    }

    public function archive(): void
    {
        if ($this->status->isArchived()) {
            throw new \DomainException('Категория уже в архиве.');
        }
        $this->status = Status::archived();
    }

    public function reinstate(): void
    {
        if ($this->status->isActive()) {
            throw new \DomainException('Категория уже активна.');
        }
        $this->status = Status::active();
    }

    public function isActive(): bool
    {
        return $this->status->isActive();
    }

    public function isArchived(): bool
    {
        return $this->status->isArchived();
    }

    public function addPost(Post $post): void
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
        }
    }

    public function removePost(Post $post): void
    {
        if ($this->posts->contains($post)) {
            $this->posts->removeElement($post);
        }
    }

    public function addChildren(Category $children): void
    {
        if (!$this->children->contains($children)) {
            $this->children->add($children);
        }
    }

    public function removeChildren(Category $children): void
    {
        if ($this->children->contains($children)) {
            $this->children->removeElement($children);
        }
    }

    public function getId(): Id
    {
        return $this->id;
    }

    public function getAuthor(): Author
    {
        return $this->author;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getSlug(): string
    {
        return $this->slug;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function getSeo(): Seo
    {
        return $this->seo;
    }

    public function getMeta(): Meta
    {
        return $this->meta;
    }

    public function getDate(): DateTimeImmutable
    {
        return $this->date;
    }

    public function getStatus(): Status
    {
        return $this->status;
    }

    public function getSort(): int
    {
        return $this->sort;
    }

    public function getParent(): ?Category
    {
        return $this->parent;
    }

    public function getChildren(): Collection
    {
        return $this->children;
    }
}

api/src/Model/Blog/Entity/Categories/Category/CategoryRepository.php
<?php

declare(strict_types=1);

namespace App\Model\Blog\Entity\Categories\Category;

use App\Model\EntityNotFoundException;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ObjectRepository;

class CategoryRepository
{
    private ObjectRepository $repo;
    private EntityManagerInterface $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->repo = $em->getRepository(Category::class);
        $this->em = $em;
    }

    public function get(Id $id): Category
    {
        if (!$category = $this->repo->find($id->getValue())) {
            throw new EntityNotFoundException('Category is not found.');
        }

        return $category;
    }

    public function add(Category $category): void
    {
        $this->em->persist($category);
    }

    public function remove(Category $category): void
    {
        $this->em->remove($category);
    }
}

api/src/Model/Blog/Entity/Categories/Category/Id.php
<?php

declare(strict_types=1);

namespace App\Model\Blog\Entity\Categories\Category;

use Ramsey\Uuid\Uuid;
use Webmozart\Assert\Assert;

class Id
{
    private string $value;

    public function __construct(string $value)
    {
        Assert::notEmpty($value);
        $this->value = $value;
    }

    public static function next(): self
    {
        return new self(Uuid::uuid4()->toString());
    }

    public function getValue(): string
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}

api/src/Model/Blog/Entity/Categories/Category/IdType.php
<?php

declare(strict_types=1);

namespace App\Model\Blog\Entity\Categories\Category;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\GuidType;

class IdType extends GuidType
{
    public const NAME = 'blog_categories_category_id';

    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        return $value instanceof Id ? $value->getValue() : $value;
    }

    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        return !empty($value) ? new Id($value) : null;
    }

    public function getName(): string
    {
        return self::NAME;
    }

    public function requiresSQLCommentHint(AbstractPlatform $platform): bool
    {
        return true;
    }
}

api/templates/app/blog/authors/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Авторы{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ path('home') }}">Главная</a></li>
        <li class="breadcrumb-item"><a href="{{ path('blog') }}">Блог</a></li>
        <li class="breadcrumb-item"><a href="{{ path('blog.authors') }}">Авторы</a></li>
        <li class="breadcrumb-item active">Создать</li>
    </ol>
{% endblock %}

{% block body %}

    <div class="card">
        <div class="card-body">

            {{ form_start(form) }}
            {{ form_widget(form) }}
            <button type="submit" class="btn btn-primary">Создать</button>
            {{ form_end(form) }}

        </div>
    </div>

{% endblock %}

api/templates/app/blog/authors/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Авторы{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ path('home') }}">Главная</a></li>
        <li class="breadcrumb-item"><a href="{{ path('blog') }}">Блог</a></li>
        <li class="breadcrumb-item"><a href="{{ path('blog.authors') }}">Авторы</a></li>
        <li class="breadcrumb-item">
            <a href="{{ path('blog.authors.show', {'id': author.id}) }}">{{ author.name.full }}</a>
        </li>
        <li class="breadcrumb-item active">Редактировать</li>
    </ol>
{% endblock %}

{% block body %}

    <div class="card">
        <div class="card-body">

            {{ form_start(form) }}
            {{ form_widget(form) }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            {{ form_end(form) }}

        </div>
    </div>

{% endblock %}

api/templates/app/blog/authors/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Авторы{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ path('home') }}">Главная</a></li>
        <li class="breadcrumb-item"><a href="{{ path('blog') }}">Блог</a></li>
        <li class="breadcrumb-item active">Авторы</li>
    </ol>
{% endblock %}

{% block body %}

    <div class="card">
        <div class="card-body">

            {{ form_start(form) }}
            <div class="row">
                <div class="col-md-2">{{ form_widget(form.name) }}</div>
                <div class="col-md-2">{{ form_widget(form.email) }}</div>
                <div class="col-md-2">{{ form_widget(form.status) }}</div>
                <div class="col-md-2">
                    <button type="submit" class="btn btn-primary">Фильтр</button>
                    <a href="{{ path('blog.authors') }}" class="btn btn-outline-secondary">Сбросить</a>
                </div>
            </div>
            {{ form_end(form) }}

        </div>
    </div>

    <div class="box">
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>{{ knp_pagination_sortable(pagination, 'Имя', 'name') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Email', 'email') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Статус', 'status') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Дата создания', 'date') }}</th>
            </tr>
            </thead>
            <tbody>
            {% for author in pagination %}
                <tr>
                    <td><a href="{{ path('blog.authors.show', {'id': author.id}) }}">{{ author.name }}</a></td>
                    <td>{{ author.email }}</td>
                    <td>{{ author_status(author.status) }}</td>
                    <td>{{ author.date | date('d.m.Y H:i') }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
    </div>

{% endblock %}

api/templates/app/blog/authors/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Авторы{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ path('home') }}">Главная</a></li>
        <li class="breadcrumb-item"><a href="{{ path('blog') }}">Блог</a></li>
        <li class="breadcrumb-item"><a href="{{ path('blog.authors') }}">Авторы</a></li>
        <li class="breadcrumb-item active">{{ author.name.full }}</li>
    </ol>
{% endblock %}

{% block body %}

    <div class="controls">
        <a href="{{ path('blog.authors.edit', {'id': author.id}) }}" class="btn btn-primary">Редактировать</a>
        <a href="{{ path('users.show', {'id': author.id}) }}" class="btn btn-primary">Посмотреть пользователя</a>
        {% if author.active and author.id.value != app.user.id %}
            <form action="{{ path('blog.authors.archive', {'id': author.id}) }}" method="post" onsubmit="return confirm('Вы уверены?')">
                <input type="hidden" name="token" value="{{ csrf_token('archive') }}" />
                <button type="submit" class="btn btn-danger">Архивировать</button>
            </form>
        {% endif %}
        {% if author.archived %}
            <form action="{{ path('blog.authors.reinstate', {'id': author.id}) }}" method="post" onsubmit="return confirm('Вы уверены?')">
                <input type="hidden" name="token" value="{{ csrf_token('reinstate') }}" />
                <button type="submit" class="btn btn-success">Восстановить</button>
            </form>
        {% endif %}
    </div>

    <div class="box">
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <th>Имя</th>
                    <td>{{ author.name.full }}</td>
                </tr>
                <tr>
                    <th>Email</th>
                    <td>{{ author.email.value }}</td>
                </tr>
                <tr>
                    <th>Статус</th>
                    <td>{{ author_status(author.status.name) }}</td>
                </tr>
                <tr>
                    <th>Дата создания</th>
                    <td>{{ author.date | date('d.m.Y H:i') }}</td>
                </tr>
            </tbody>
        </table>
    </div>

{% endblock %}